ARG tag=0.1.0
ARG image=kazuh/urent-php:$tag

FROM $image as tmp

FROM nginx:alpine
WORKDIR /var/www
EXPOSE 80

COPY . .
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=tmp /var/www/public .

RUN chown -R nginx:nginx /var/cache/

RUN chmod -R 755 /var/www
RUN chown -R nginx:nginx /var/www

# USER nginx

CMD [ "nginx", "-g", "daemon off;" ]    